java:
  applicationPort: 7081
  image: 'hmctspublic.azurecr.io/rpe/spring-boot-template:latest'

  ingressHost: rpe-spring-boot-template-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

  aadIdentityName: rpe
  environment:
